
CREATE TABLE `T_INET_ACTIVITY` (
  `ID_ACTIVITY` int(11) NOT NULL AUTO_INCREMENT COMMENT '活动主键',
  `NAME` varchar(128) NOT NULL COMMENT '活动名称',
  `CHANNEL` varchar(64) NOT NULL COMMENT '活动渠道（ALL， MOBILE， PC）',
  `BEGIN_DATE` date NOT NULL COMMENT '活动开始日期',
  `EXPIRE_DATE` date NOT NULL COMMENT '活动截止日期',
  `RECEIVE_MAX` smallint(6) DEFAULT NULL COMMENT '最大领取次数',
  `CRT_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID_ACTIVITY`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8;

CREATE TABLE `T_USER_ACTIVITY` (
  `ID_USER_ACTIVITY` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ID_INET_ACTIVITY` int(11) DEFAULT NULL COMMENT '活动主键',
  `USER_ID` varchar(128) DEFAULT NULL COMMENT '用户ID',
  `RECEIVE_CODE` varchar(128) DEFAULT NULL COMMENT '活动领取码',
  `CRT_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPT_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID_USER_ACTIVITY`),
  KEY `IDX_INET_ACT_USER_ID` (`USER_ID`) USING BTREE,
  KEY `IDX_INET_ACT_RECEIVE_CODE` (`RECEIVE_CODE`) USING BTREE,
  KEY `IDX_ACTIVITYID_RECEIVECODE` (`RECEIVE_CODE`,`ID_INET_ACTIVITY`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `T_USER_ACTIVITY_RECEIVE` (
  `ID_USER_ACT_RCV` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ID_USER_ACTIVITY` int(11) NOT NULL COMMENT '用户转发活动ID',
  `ID_INET_ACTIVITY` int(11) DEFAULT NULL COMMENT '互联网活动ID',
  `RECEIVE_USER_ID` varchar(128) DEFAULT NULL COMMENT '领取用户ID',
  `STATUS` char(1) DEFAULT NULL,
  `CRT_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `EXT_DATA1` varchar(64) DEFAULT NULL,
  `EXT_DATA2` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`ID_USER_ACT_RCV`),
  KEY `IDX_INET_RECEIVE_UN` (`RECEIVE_USER_ID`,`ID_INET_ACTIVITY`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `T_USER_RELATION` (
  `USER_ID` varchar(128) NOT NULL COMMENT '大智慧账号',
  `RELATION` mediumtext COMMENT '大智慧账号的好友关系',
  PRIMARY KEY (`USER_ID`),
  KEY `IDX_USER_RALATION` (`USER_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;