
DROP TABLE IF EXISTS `T_INET_ACTIVITY`;
CREATE TABLE `T_INET_ACTIVITY` (
  `ID_ACTIVITY` int(11) NOT NULL AUTO_INCREMENT COMMENT '活动主键',
  `NAME` varchar(128) NOT NULL COMMENT '活动名称',
  `CONTENT` varchar(1024) DEFAULT NULL COMMENT '活动内容',
  `SPONSOR` varchar(64) DEFAULT NULL COMMENT '活动发起者（可以使部门）',
  `CHANNEL` varchar(64) NOT NULL COMMENT '活动渠道（ALL， GW， WX）',
  `EXPIRE_DATE` date NOT NULL COMMENT '活动截止日期',
  `BEGIN_DATE` date NOT NULL COMMENT '活动开始日期',
  `POLICY_TYPE` varchar(16) DEFAULT NULL COMMENT '活动策略类型（如豆， 彩币等）',
  `RECEIVE_MAX` int(11) DEFAULT NULL COMMENT '最大领取次数',
  `ACT_FRWD_SRV_NAME` varchar(128) DEFAULT NULL COMMENT '为活动转发者提供的服务',
  `ACT_FRWD_SRV_ARGS` varchar(256) DEFAULT NULL COMMENT '为活动转发者提供的服务相关参数',
  `ACT_RCV_SRV_NAME` varchar(128) DEFAULT NULL COMMENT '为活动领取者提供的服务',
  `ACT_RCV_SRV_ARGS` varchar(256) DEFAULT NULL COMMENT '为活动领取者提供的服务相关参数',
  `ACT_RCV_POSTSRV_NAME` varchar(128) DEFAULT NULL COMMENT '为活动领取者提供的后置服务',
  `ACT_RCV_POSTSRV_ARGS` varchar(256) DEFAULT NULL COMMENT '为活动领取者提供的后置服务相关参数',
  `ACT_DONE_SRV_NAME` varchar(128) DEFAULT NULL COMMENT '活动完成后的回调服务',
  `ACT_DONE_SRV_ARGS` varchar(256) DEFAULT NULL COMMENT '活动完成后的回调服务相关参数',
  `ACT_START_SRV_NAME` varchar(128) DEFAULT NULL COMMENT '活动开始后的回调服务',
  `ACT_START_SRV_ARGS` varchar(256) DEFAULT NULL COMMENT '活动开始后的回调服务相关参数',
  `CRT_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `MAX_FWD_COUNT` smallint(6) DEFAULT NULL COMMENT '单个活动每个用户最大转发次数',
  `MAX_JOIN_COUNT` smallint(6) DEFAULT NULL COMMENT '单个活动每个用户可以消费邀请码的最大数目',
  `USER_TYPE` char(10) DEFAULT NULL COMMENT '用户类型',
  `DONE_SRV_TRIGGER_TYPE` char(10) DEFAULT NULL COMMENT '活动转发者邀请码被满足数目的好友消费之后服务的触发方式（1 自动 2 手动）',
  PRIMARY KEY (`ID_ACTIVITY`)
) ENGINE=InnoDB   DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `T_USER_ACTIVITY`;
CREATE TABLE `T_USER_ACTIVITY` (
  `ID_USER_ACTIVITY` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ID_INET_ACTIVITY` int(11) DEFAULT NULL COMMENT '活动主键',
  `USER_ID` varchar(128) DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` varchar(128) DEFAULT NULL COMMENT '用户名称',
  `RECEIVE_MAX` int(11) NOT NULL COMMENT '最多可领取次数',
  `RECEIVE_COUNT` int(11) DEFAULT NULL COMMENT '被领取次数',
  `RECEIVE_CODE` varchar(128) DEFAULT NULL COMMENT '活动领取码',
  `EXPIRE_DATE` date NOT NULL COMMENT '领取截止日期， 同活动截止日期',
  `CHANNEL` varchar(64) DEFAULT NULL COMMENT '活动转发渠道',
  `ACT_FRWD_SRV_NAME` varchar(128) DEFAULT NULL COMMENT '为活动转发者提供的服务',
  `ACT_FRWD_SRV_ARGS` varchar(256) DEFAULT NULL COMMENT '为活动转发者提供的服务相关参数',
  `ACT_RCV_SRV_NAME` varchar(128) DEFAULT NULL COMMENT '为活动领取者提供的服务',
  `ACT_RCV_SRV_ARGS` varchar(256) DEFAULT NULL COMMENT '为活动领取者提供的服务相关参数',
  `ACT_RCV_POSTSRV_NAME` varchar(128) DEFAULT NULL COMMENT '为活动领取者提供的后置服务',
  `ACT_RCV_POSTSRV_ARGS` varchar(256) DEFAULT NULL COMMENT '为活动领取者提供的后置服务相关参数',
  `ACT_DONE_SRV_NAME` varchar(128) DEFAULT NULL COMMENT '活动完成后的回调服务',
  `ACT_DONE_SRV_ARGS` varchar(256) DEFAULT NULL COMMENT '活动完成后的回调服务相关参数',
  `ACT_START_SRV_NAME` varchar(128) DEFAULT NULL COMMENT '活动开始后的回调服务',
  `ACT_START_SRV_ARGS` varchar(256) DEFAULT NULL COMMENT '活动开始后的回调服务相关参数',
  `REQUEST_TIME` datetime DEFAULT NULL COMMENT '请求时间',
  `ID_REQUEST` varchar(64) DEFAULT NULL COMMENT '请求流水号',
  `MAX_FWD_COUNT` smallint(6) DEFAULT NULL COMMENT '单个活动每个用户最大转发次数',
  `MAX_JOIN_COUNT` smallint(6) DEFAULT NULL COMMENT '单个活动每个用户可以消费邀请码的最大数目',
  `USER_TYPE` char(10) DEFAULT NULL COMMENT '用户类型',
  `DONE_SRV_TRIGGER_TYPE` char(10) DEFAULT NULL COMMENT '活动转发者邀请码被满足数目的好友消费之后服务的触发方式（1 自动 2 手动）',
  `CRT_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPT_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID_USER_ACTIVITY`),
  KEY `IDX_INET_ACT_USER_ID` (`USER_ID`) USING BTREE,
  KEY `IDX_INET_ACT_RECEIVE_CODE` (`RECEIVE_CODE`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `T_USER_ACTIVITY_RECEIVE`;
CREATE TABLE `T_USER_ACTIVITY_RECEIVE` (
  `ID_USER_ACT_RCV` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ID_USER_ACTIVITY` int(11) NOT NULL COMMENT '用户转发活动ID',
  `ID_INET_ACTIVITY` int(11) DEFAULT NULL COMMENT '互联网活动ID',
  `RECEIVE_USER_ID` varchar(128) DEFAULT NULL COMMENT '领取用户ID',
  `RECEIVE_USER_NAME` varchar(128) DEFAULT NULL COMMENT '领取用户名称',
  `RECEIVE_TIME` datetime DEFAULT NULL COMMENT '领取时间',
  `CHANNEL` varchar(64) DEFAULT NULL COMMENT '领取活动渠道',
  `STATUS` char(1) DEFAULT NULL COMMENT '领取状态(1:成功， 0未成功）',
  `REF_NO` varchar(64) DEFAULT NULL COMMENT '外部引用编码（如彩票码）',
  `MEMO` varchar(256) DEFAULT NULL COMMENT '备注',
  `CRT_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`ID_USER_ACT_RCV`),
  KEY `IDX_INET_RECEIVE_UN` (`ID_INET_ACTIVITY`,`RECEIVE_USER_ID`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `T_SERVICE_CLIENT`;
CREATE TABLE `T_SERVICE_CLIENT` (
  `CLIENT_CODE` varchar(32) NOT NULL COMMENT '客户端编码',
  `CLIENT_KEY` varchar(64) NOT NULL COMMENT '通讯秘钥',
  `CLIENT_DESC` varchar(128) DEFAULT NULL COMMENT '客户端描述',
  `STATUS` char(1) NOT NULL COMMENT '客户端状态(1, 正常, 0, 冻结)',
  `CRT_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPT_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`CLIENT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `T_SRV_EXEC_REQUEST`;
CREATE TABLE `T_SRV_EXEC_REQUEST` (
  `ID_SRV_EXEC_REQUEST` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `REF_NO` int(11) NOT NULL COMMENT '服务执行由来',
  `DONEE_ID` varchar(64) DEFAULT NULL COMMENT '受赠人ID',
  `DONEE_NAME` varchar(128) DEFAULT NULL COMMENT '受赠人名称',
  `SRV_TYPE` varchar(2) NOT NULL COMMENT '服务类型：1-START ，2-FRWD，3-RCV，4-DONE, 5-POSTRCV',
  `SRV_NAME` varchar(128) NOT NULL COMMENT '服务名称',
  `SRV_ARGS` varchar(256) DEFAULT NULL COMMENT '服务参数',
  `EXEC_RESULT` varchar(1024) DEFAULT NULL COMMENT 'JASON 字符串',
  `REQUEST_TIME` datetime DEFAULT NULL COMMENT '请求时间',
  `FINISH_TIME` datetime DEFAULT NULL COMMENT '完成时间',
  `STATUS` char(1) DEFAULT NULL COMMENT '状态（1，成功， 0， 失败）',
  `ERROR_CODE` varchar(16) DEFAULT NULL COMMENT '错误码',
  `ERROR_DESC` varchar(256) DEFAULT NULL COMMENT '错误描述',
  `CRT_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `EXECUTE_COUNT` int(11) DEFAULT '0',
  PRIMARY KEY (`ID_SRV_EXEC_REQUEST`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `T_OTC_PRODUCT`;
CREATE TABLE `T_OTC_PRODUCT` (
  `PROD_CODE` varchar(64) NOT NULL COMMENT '主键, 产品编码',
  `PROD_NAME` varchar(100) DEFAULT NULL COMMENT '产品名称',
  `PROD_DESC` varchar(128) DEFAULT NULL COMMENT '产品描述',
  `PROD_RATE` varchar(20) DEFAULT NULL COMMENT '产品利率',
  `BUY_BASE_LIMIT` int(11) DEFAULT NULL COMMENT '购买基础额度',
  `APPLY_DATE` char(8) NOT NULL COMMENT '申购日期',
  `ISSUE_DATE` char(8) DEFAULT NULL COMMENT '发行日期',
  `ISSUE_SHARE` int(11) DEFAULT NULL COMMENT '发行总份额',
  PRIMARY KEY (`PROD_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `T_ACTIVITY_OTC_PRODUCT`;
CREATE TABLE `T_ACTIVITY_OTC_PRODUCT` (
  `ID_ACTIVITY_OTC_PRODUCT` int(11) NOT NULL COMMENT '主键',
  `PRODUCT_CODE` varchar(64) NOT NULL COMMENT '产品编号',
  `ID_ACTIVITY` int(11) NOT NULL COMMENT '互联网活动主键',
  PRIMARY KEY (`ID_ACTIVITY_OTC_PRODUCT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `T_ACTIVITY_USER_LIMIT`;
CREATE TABLE `T_ACTIVITY_USER_LIMIT` (
  `ID_ACTIVITY_USER_LIMIT` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ID_ACTIVITY` int(11) NOT NULL COMMENT '活动主键',
  `USER_ID` varchar(64) NOT NULL COMMENT '用户主键',
  `FIRM_ACCT` varchar(64) DEFAULT NULL COMMENT '用户湘财资金账户',
  `BASE_LIMIT` int(11) DEFAULT NULL COMMENT '基础额度',
  `EXT_LIMIT` int(11) DEFAULT NULL COMMENT '扩展额度',
  `CRT_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPT_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID_ACTIVITY_USER_LIMIT`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `T_PLTUSER_FIRMACCT`;
CREATE TABLE `T_PLTUSER_FIRMACCT` (
  `ID_PLTUSER_FIRMACCT` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PLTUSER` varchar(64) NOT NULL COMMENT '平台用户ID(微信ID)',
  `FIRM_ACCT` varchar(64) NOT NULL COMMENT '用户湘财资金账户',
  `CHANNEL` varchar(64) NOT NULL COMMENT '数据来源',
  `WX_APP_ID` varchar(64) DEFAULT NULL,
  `OPENACCT_CHANNEL` varchar(32) DEFAULT NULL,
  `CRT_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPT_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID_PLTUSER_FIRMACCT`),
  UNIQUE KEY `ID_PTLUSER` (`ID_PLTUSER`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;


--20150327
ALTER TABLE T_OTC_PRODUCT CHANGE APPLY_DATE APPLY_START_DATE CHAR(8) NOT NULL;
ALTER TABLE T_OTC_PRODUCT ADD  COLUMN APPLY_END_DATE CHAR(8) NOT NULL;
ALTER TABLE T_OTC_PRODUCT ADD  COLUMN RISK_LEVEL VARCHAR(8) ;
ALTER TABLE T_OTC_PRODUCT ADD  COLUMN PROD_CYCLE VARCHAR(8) ;
ALTER TABLE T_OTC_PRODUCT ADD  COLUMN PROD_FEATURE VARCHAR(256) ;
ALTER TABLE T_OTC_PRODUCT ADD  COLUMN PROD_CONTRACT VARCHAR(5000) ;
ALTER TABLE T_OTC_PRODUCT ADD  COLUMN RISK_DISCLOSURE_LETTER VARCHAR(5000) ;


--20150424
ALTER TABLE T_INET_ACTIVITY ADD  COLUMN EXT_DATA1 VARCHAR(100) ;
ALTER TABLE T_INET_ACTIVITY ADD  COLUMN EXT_DATA2 VARCHAR(100) ;

ALTER TABLE T_USER_ACTIVITY_RECEIVE ADD  COLUMN EXT_DATA1 VARCHAR(100) ;
ALTER TABLE T_USER_ACTIVITY_RECEIVE ADD  COLUMN EXT_DATA2 VARCHAR(100) ;

CREATE TABLE T_ACTIVITY_UNIVERSITY_GAMES(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	USER_ID VARCHAR(64)  NOT NULL ,
	ENTRY_CODE VARCHAR(10) NOT NULL,
	REGISTRATION_TIME DATETIME NOT NULL,
	CRT_TIME DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--20150526 将T_USER_ACTIVITY_RECEIVE的`EXT_DATA1`和`EXT_DATA2`字段长度改为256
ALTER TABLE `T_USER_ACTIVITY_RECEIVE`
MODIFY COLUMN `EXT_DATA1`  varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `CRT_DATE`,
MODIFY COLUMN `EXT_DATA2`  varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `EXT_DATA1`;

--20150528 将T_USER_ACTIVITY_RECEIVE的`EXT_DATA1`和`EXT_DATA2`字段回复为原来的长度64
ALTER TABLE `T_USER_ACTIVITY_RECEIVE`
MODIFY COLUMN `EXT_DATA1`  varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `CRT_DATE`,
MODIFY COLUMN `EXT_DATA2`  varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `EXT_DATA1`;


CREATE TABLE `T_USER_STOCK_POOL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `USER_ID` varchar(128) DEFAULT NULL COMMENT '大智慧用户名（包含表t_User_activity.userId, 表t_User_activity_receive.receivedUserId，两字段值相同）',
  `HAS_STOCK_POOL` int(2) DEFAULT '0' COMMENT '是否股票池 1-是,2-没有',
  `YIELD_RATE` varchar(32) DEFAULT NULL COMMENT '股票池收益率',
  `DEVICE_ID` varchar(128) DEFAULT NULL COMMENT '设备号',
  `CRT_DATE` datetime DEFAULT NULL COMMENT '创建时间',
  `UPT_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;